# Generated by Django 5.2.7 on 2025-10-25 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Judgment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence1', models.TextField()),
                ('sentence2', models.TextField()),
                ('sentence1_norm', models.TextField()),
                ('sentence2_norm', models.TextField()),
                ('similarity', models.FloatField()),
                ('label', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('sentence1_norm', 'sentence2_norm')},
            },
        ),
    ]
